# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a4fc790f-72fc-467b-bd20-69cc09945327";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a4fc790f-72fc-467b-bd20-69cc09945327".device = "/dev/disk/by-uuid/a4fc790f-72fc-467b-bd20-69cc09945327";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C9FC-43CC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.virtualbox.guest.enable = true;
}
